branches:
  only:
    - master

services:
  - docker

script:
  - docker build -t ruby-build-env .

after_success:
  - date=$(date "+%Y%m%d")
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker tag ruby-build-env rubylang/ruby-build-env:"${date}"
  - docker push rubylang/ruby-build-env:"${date}"
  - docker tag ruby-build-env rubylang/ruby-build-env:latest
  - docker push rubylang/ruby-build-env:latest
